name=MicroTone
version=1.0.0
author=Ali Najafian
maintainer=<Alinajafian81@gmail.com>
sentence=low-flash pulse train library with attiny13
paragraph=A very simple library to create pulse train with an attiny 13 MCU
category=Signal Input/Output
url=
architectures=Attiny13A
