name=MicroTone
version=2.0.1
author=Ali Najafian
maintainer=<Alinajafian81@gmail.com>
sentence=low-flash high-performance pulse train library with Attiny13 or Atmega8/A
paragraph=A simple library to create pulse train with an Attiny13A/L or Atmega8/A MCUs without ANY CPU usage. 
category=Signal Input/Output
url=https://github.com/Master811129/MicroTone
architectures=avr
